apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
spec:
  type: NodePort
  selector:
    app: app-test
  ports:
  - port: 8080  
    targetPort: 8080
    nodePort: 30001
  
