apiVersion: v1
kind: ConfigMap
metadata:
  name: db-vars-for-app
  namespace: app
data:
  POSTGRES_DB: appdb
  POSTGRES_HOST: db-service.db.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres