apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: db
spec:
  type: ClusterIP
  # clusterIP: None
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
