apiVersion: v1
kind: PersistentVolume
metadata:
  name: disk-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Recycle
  # storageClassName: slow
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
  hostPath:
    # path: /pv-data #linux
    path: "F:\\Data" #windows
    type: DirectoryOrCreate